### PR TITLE
[Issue 2391] Extension - Handle fallback for online content

### PR DESCRIPTION
**Pull request by Thiendekaco**
**Describe the task**
Handle fallback for online content
- [x] Create folder data
- [x] Improve function `fetchStaticData` with fallback data

### CODE REVIEW

**Comment by saltict** [comment]
🚀 Deployed on https://pr-2422--sw-web-runner.netlify.app

**Review by cerwik8 — COMMENTED** [review]
Tkank's

**Comment by saltict** [comment]
> Tkank's

Hi, how you can review for this PR?

**Review by saltict — CHANGES_REQUESTED** [review]
@Thiendekaco please change all data file to json format

**Pull request closed without merging**
