### PR TITLE
Koni/dev/issue 143

### PR DESCRIPTION
**Pull request by lw-cdm**
Pull request for #143 
Implement Send fund UI with new Send Fund API:
- Support sending fund sub token of some networks
- Support sending fund for evm networks

### CODE REVIEW

**Comment by sokol142** [comment]
@lw-cdm 
1. Can't send token SUB (Subsocial Solochain)
- Actual: Send Fund Failed although the account have enough balance
image

2. Display token incorrect in Resend view
image

**Comment by sokol142** [comment]
3. Send fund failed when the account has no balance of main token
  - My suggestion: When choose token to send fund, display message err "Transfer is not supported when account has no balance of main token"
Bug_215

**Comment by sokol142** [comment]
4. Bug when Donate
Bug_215_Donate

**Comment by sokol142** [comment]
- [ ] Loading infinity when value too low to create account due to existential deposit on firefox browser
**Steps:**
1. Open firefox browser
2. Open extension
3. Click on Send fund button
4. Select PHA (karura) token
5. Input valid data
6. Click on Sign & Submit
**Actual**: Loading infinity
**Expected:** Submit successful and display Send Fund Result screen
bug_215_sendfund_firefox

_Notes: On Brave browser, display Send Fund Result screen with message: "Send Fund Fail
There was a problem with your request. You can track its progress on the Transaction History page.
Value too low to create account due to existential deposit"_
image

**Comment by sokol142** [comment]
@Quangdm-cdm check issues: Display message warning on Donate screen, but Send Fund not display.
=> You check & update 
improve_donate

**Comment by sokol142** [comment]
- [ ] Improve experience in case the account has no balance of main token
Expected: Always disable Make Transfer button when transfer error
image

**Review by saltict — APPROVED** [review]

**Pull request merged**
